baseurl = "/"
languageCode = "en-us"
title = "Strata"
theme = "hugo-strata-theme"
disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Your name"
	description = "Describe your website"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "**Tervetuloa**, tällä sivustolla sijaitsee <br><nimi> blogi <br>."
		# The icons will be shown if you enter your username
		twitter = "spf13"
		github = "spf13"
		dribbble = ""
		facebook = ""
		googleplus = ""
		flickr = ""
		linkedin = ""

		copyright = [
			"&copy; <nimi>",
			"Websivut: [HTML5 UP](//html5up.net)",
			"Kuvat: [Unsplash](//unsplash.com/)"
		]


	[params.about]
		hide  = false
		title = "Tässä blogissa takerrumme...jatkuu"
		content = "Toivottavasti artikkelien sisältö...jatkuu"


	[params.portfolio]
		hide  = false
		title = "Käynnissä olevia projekteja"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/01.jpg"
			thumb = "thumbs/01.jpg"
			title = "Projekti"
			description = "Projektin kuvaus"

		[[params.portfolio.gallery]]
			image = "fulls/02.jpg"
			thumb = "thumbs/02.jpg"
			title = "Projekti"
			description = "Projektin kuvaus"

		[[params.portfolio.gallery]]
			image = "fulls/03.jpg"
			thumb = "thumbs/03.jpg"
			title = "Projekti"
			description = "Projektin kuvaus"

		[[params.portfolio.gallery]]
			image = "fulls/04.jpg"
			thumb = "thumbs/04.jpg"
			title = "Projekti"
			description = "Projektin kuvaus"

	[params.recentposts]
		hide  = false
		title = "Viimeisimmät blogi-kirjoitukset"

	[params.contact]
		hide  = false
		title = "Ota yhteyttä"
		content = "Kiinnoistuitko sisällöstä, haluaisitko kommentoida tai keskustella lisää: alta voit kirjoittaa minulle."

		address = [
			"Helsinki, Suomi",
		]
		phone = "000-000-0000"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "p.santtuvp@gmail.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Nimi"
			email = "Sähköpostiosoite"
			message = "Viesti"
			submit = "Lähetä viesti"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Koti"
	url  = "/"
	weight = 0

[[menu.main]]
	name = "Minusta"
	url  = "minusta"
	weight = 5

[[menu.main]]
	name = "Blog"
	url  = "post/"
	weight = 10
